import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

<<<<<<< Updated upstream
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

=======
>>>>>>> Stashed changes
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
<<<<<<< Updated upstream
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
=======
      <body>
        <div>
          <div></div>
          {/* Only show Navbar and Footer if it's not the login or register page */}
          <Providers>
            {!isAuthPage && <Navbar />}
            <main>{children}</main>
            {!isAuthPage && <Footer />}
          </Providers>
        </div>
>>>>>>> Stashed changes
      </body>
    </html>
  );
}
